// Mock data for development
export const mockProducts = [
  {
    id: "m1",
    name: "Tokyo Beats Vinyl",
    description: "Limited edition vinyl featuring the best of Tokyo's electronic music scene.",
    price: 29.99,
    countInStock: 15,
    rating: 4.5,
    numReviews: 12,
    images: ["https://images.unsplash.com/photo-1614613535308-eb5fbd3d2c17?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3"],
    category: "music",
    culture: "tokyo",
    isFeatured: true,
    sizes: ["N/A"],
    selectedSize: "N/A"
  },
  {
    id: "m2",
    name: "New York Underground Mixtape",
    description: "Raw and authentic sounds from NYC's underground hip-hop scene.",
    price: 19.99,
    countInStock: 20,
    rating: 4.8,
    numReviews: 24,
    images: ["https://images.unsplash.com/photo-1603048588665-791ca8aea617?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3"],
    category: "music",
    culture: "newyork",
    isFeatured: true,
    sizes: ["N/A"],
    selectedSize: "N/A"
  },
  {
    id: "m3",
    name: "Lagos Afrobeats Collection",
    description: "The essential collection of contemporary Afrobeats from Lagos.",
    price: 24.99,
    countInStock: 8,
    rating: 4.7,
    numReviews: 18,
    images: ["https://images.unsplash.com/photo-1610216705422-caa3fcb6d158?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3"],
    category: "music",
    culture: "lagos",
    isFeatured: false,
    sizes: ["N/A"],
    selectedSize: "N/A"
  },
  {
    id: "m4",
    name: "Seoul K-Pop Classics",
    description: "The definitive compilation of K-Pop hits that changed global music.",
    price: 22.99,
    countInStock: 12,
    rating: 4.9,
    numReviews: 32,
    images: ["https://images.unsplash.com/photo-1578380277096-75063e5858d3?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3"],
    category: "music",
    culture: "seoul",
    isFeatured: true,
    sizes: ["N/A"],
    selectedSize: "N/A"
  },
  {
    id: "f1",
    name: "Harajuku Street Hoodie",
    description: "Vibrant hoodie inspired by Tokyo's Harajuku district fashion.",
    price: 59.99,
    countInStock: 10,
    rating: 4.6,
    numReviews: 14,
    images: ["https://images.unsplash.com/photo-1572495673508-62a6b369c380?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3"],
    category: "fashion",
    culture: "tokyo",
    isFeatured: true,
    sizes: ["S", "M", "L", "XL"],
    selectedSize: "M"
  },
  {
    id: "f2",
    name: "Brooklyn Graphic Tee",
    description: "Authentic Brooklyn-inspired graphic t-shirt with vintage print.",
    price: 34.99,
    countInStock: 25,
    rating: 4.4,
    numReviews: 22,
    images: ["https://images.unsplash.com/photo-1503341733017-1901578f9f1e?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3"],
    category: "fashion",
    culture: "newyork",
    isFeatured: false,
    sizes: ["S", "M", "L", "XL", "XXL"],
    selectedSize: "L"
  },
  {
    id: "f3",
    name: "Lagos Print Jacket",
    description: "Contemporary jacket featuring traditional Nigerian patterns.",
    price: 79.99,
    countInStock: 5,
    rating: 4.9,
    numReviews: 9,
    images: ["https://images.unsplash.com/photo-1591369822096-ffd140ec948f?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3"],
    category: "fashion",
    culture: "lagos",
    isFeatured: true,
    sizes: ["S", "M", "L"],
    selectedSize: "M"
  },
  {
    id: "f4",
    name: "Seoul Minimalist Jacket",
    description: "Clean, minimalist design inspired by Seoul's contemporary fashion.",
    price: 89.99,
    countInStock: 7,
    rating: 4.7,
    numReviews: 16,
    images: ["https://images.unsplash.com/photo-1551488831-00ddcb6c6bd3?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3"],
    category: "fashion",
    culture: "seoul",
    isFeatured: true,
    sizes: ["S", "M", "L", "XL"],
    selectedSize: "M"
  },
  {
    id: "a1",
    name: "Tokyo Tech Backpack",
    description: "Futuristic backpack with LED accents inspired by Tokyo's tech culture.",
    price: 69.99,
    countInStock: 8,
    rating: 4.8,
    numReviews: 11,
    images: ["https://images.unsplash.com/photo-1581605405669-fcdf81165afa?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3"],
    category: "accessories",
    culture: "tokyo",
    isFeatured: true,
    sizes: ["N/A"],
    selectedSize: "N/A"
  },
  {
    id: "a2",
    name: "NYC Graffiti Cap",
    description: "Snapback cap featuring authentic New York graffiti art.",
    price: 29.99,
    countInStock: 18,
    rating: 4.3,
    numReviews: 27,
    images: ["https://images.unsplash.com/photo-1588850561407-ed78c282e89b?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3"],
    category: "accessories",
    culture: "newyork",
    isFeatured: false,
    sizes: ["One Size"],
    selectedSize: "One Size"
  },
  {
    id: "a3",
    name: "Lagos Beaded Necklace",
    description: "Handcrafted beaded necklace made by Nigerian artisans.",
    price: 39.99,
    countInStock: 6,
    rating: 5.0,
    numReviews: 8,
    images: ["https://images.unsplash.com/photo-1599459183200-89f6f64c1a3c?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3"],
    category: "accessories",
    culture: "lagos",
    isFeatured: true,
    sizes: ["N/A"],
    selectedSize: "N/A"
  },
  {
    id: "a4",
    name: "Seoul Minimalist Watch",
    description: "Elegant timepiece with clean lines inspired by Korean design.",
    price: 119.99,
    countInStock: 4,
    rating: 4.9,
    numReviews: 15,
    images: ["https://images.unsplash.com/photo-1524592094714-0f0654e20314?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3"],
    category: "accessories",
    culture: "seoul",
    isFeatured: true,
    sizes: ["N/A"],
    selectedSize: "N/A"
  }
]; 